### ISSUE TITLE
No module AppKit

### ISSUE THREAD

**Issue by masterit-dev** [Townk/ansible-beautiful-output#2]
Hi,

Thanks for your contribution. I was hoping getting ride of text-crazy ansible stdout ouput... But ... python beat/bite me !!!

I configured my ansible as you suggested ans install the requirements : ```pip3 install watchdog``` but I hit this error :

```
ERROR! Unexpected Exception, this is probably a bug: No module named 'AppKit'
```

When I try to install it (```pip3 install AppKit```), it seems to be OK :
 
```
Requirement already satisfied: AppKit in /home/fozodlen/.local/lib/python3.8/site-packages (0.2.8)
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (from AppKit) (3.36.0)
Requirement already satisfied: beautifulsoup4 in /home/fozodlen/.local/lib/python3.8/site-packages (from AppKit) (4.9.3)
Requirement already satisfied: flask in /home/fozodlen/.local/lib/python3.8/site-packages (from AppKit) (1.1.2)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject->AppKit) (1.16.2)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /home/fozodlen/.local/lib/python3.8/site-packages (from beautifulsoup4->AppKit) (2.2.1)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask->AppKit) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in /home/fozodlen/.local/lib/python3.8/site-packages (from flask->AppKit) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/fozodlen/.local/lib/python3.8/site-packages (from flask->AppKit) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/fozodlen/.local/lib/python3.8/site-packages (from flask->AppKit) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->flask->AppKit) (1.1.0)
```

Any idea what I did wrong? pip3 is the problem?

Sincerly,

**Comment by Townk** [comment]
Thanks for checking this out. To be honest with you, it's being a long time since I use this package! I will try to find some time  on the next week to look into this for you.

**Comment by Townk** [comment]
After a long time digging into this, all I could find is that a dependency library for this package is requiring python AppKit. The solution here is to add AppKit as you pip dependency as well.

**Comment by masterit-dev** [comment]
> After a long time digging into this, all I could find is that a dependency library for this package is requiring python AppKit. The solution here is to add AppKit as you pip dependency as well.

That's what I did, the problem is certainly on my system. I'll post if I find a solution. Thanks for digging into this.

**Comment by perfectayush** [comment]
I looked into the code for this, and after looking at code, I realize that `watchdog` classes/code imported in beautiful_output.py, is not being used at all. Just by removing those imports and removing `FileSystemEventHandler` from class `CallbackModule`, I can use the beautiful_output.py directly, without any pypi dependency.
